### ISSUE TITLE
Please add build instructions

### ISSUE THREAD

**Issue by pold500** [haskell/old-time#9] opened 2017-11-22 14:43 UTC
Please add build instructions.

I don't know what to do after call to ./configure

**Comment by hvr** [comment] 2017-11-23 10:41
I assume this is related to your comment over at https://github.com/haskell/old-time/issues/5#issuecomment-346363887

The problem is that there's very few of us who actually use Windows, which is the only arch which seems to have users running into this unfortunate "C compiler cannot create executables" issue. I'd love to see a short troubleshooting section added to the README specifically describing how to resolve this issue for Windows users.

/cc @Mistuke @gbaz

**Comment by pold500** [comment] 2017-11-23 11:02
@hvr How do you look if I make a pull request resolving this issue for windows users? I'm not an expert at autoconf and automake though, so it will need polishing and review.

**Comment by gbaz** [comment] 2017-11-23 17:13
@pold -- are you running configure manually!? You should be calling it via cabal-install. If you've installed the windows platform and configured step 2 properly, which sets up the paths in the cabal-install config file, then it should work properly. The thing I noticed in your pastebin is the line `uname -s = CYGWIN_NT-10.0`.

If everything is configured correctly, the msys directory should take precedence over the cygwin one.

**Comment by gbaz** [comment] 2018-01-06 07:20
Closing this in favor of https://github.com/haskell/cabal/issues/4901 which is how it will be resolved

**Closed as completed by gbaz** 2018-01-06 07:20 UTC
Labels: help wanted
