### ISSUE TITLE
Fails to install on Windows/Cygwin

### ISSUE THREAD

**Issue by tebello-thejane** [haskell/old-time#2] opened 2015-09-01 13:39 UTC
Under `Cygwin`, when one tries to install `old-time`, the following happens:

```
$ cabal install old-time
Resolving dependencies...
Configuring old-locale-1.0.0.7...
Building old-locale-1.0.0.7...
Installed old-locale-1.0.0.7
Configuring old-time-1.1.0.3...
Building old-time-1.1.0.3...
Failed to install old-time-1.1.0.3
Build log ( C:\Users\thejanet\AppData\Roaming\cabal\logs\old-time-1.1.0.3.log ):
Building old-time-1.1.0.3...
Preprocessing library old-time-1.1.0.3...
Time.hsc: In function 'main':
Time.hsc:361:5: error: 'struct tm' has no member named 'tm_zone'
Time.hsc:362:5: error: 'struct tm' has no member named 'tm_gmtoff'
compiling dist\build\System\Time_hsc_make.c failed (exit code 1)
command was: C:\dev\ghc-7.10.2\mingw\bin\gcc.exe -c dist\build\System\Time_hsc_make.c -o dist\build\System\Time_hsc_make.o -D__GLASGOW_HASKELL__=710 -Dmingw32_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1 -Dmingw32_HOST_OS=1 -Dx86_64_HOST_ARCH=1 -Iinclude -Idist\build\autogen -include dist\build\autogen\cabal_macros.h -IC:\dev\ghc-7.10.2\lib\base_GDytRqRVSUX7zckgKqJjgw\include -IC:\dev\ghc-7.10.2\lib\integ_2aU3IZNMF9a7mQ0OzsZ0dS\include -IC:\dev\ghc-7.10.2\lib/include -IC:\dev\ghc-7.10.2/lib/include/
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/timeb.h usability... yes
checking sys/timeb.h presence... yes
checking for sys/timeb.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for ftime... yes
checking for gmtime_r... yes
checking for localtime_r... yes
checking for gettimeofday... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for struct tm.tm_zone... yes
checking whether time.h and sys/time.h may both be included... yes
checking for sys/time.h... (cached) yes
checking whether altzone is declared... no
configure: creating ./config.status
config.status: creating include/HsTimeConfig.h
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
cabal.exe: Error: some packages failed to install:
old-time-1.1.0.3 failed during the building phase. The exception was:
ExitFailure 1
```

I'm running GHC 7.10.2 under Cygwin on Windows 7 x64.

**Comment by vitorsvieira** [comment] 2015-09-03 15:58
+1

**Comment by ndmitchell** [comment] 2015-09-16 18:10
Have you tried using MinGHC? Does the bug replicate there? https://github.com/fpco/minghc

**Comment by tebello-thejane** [comment] 2015-09-17 15:36
It works under `MinGHC`. Thanks. 

Basically, if I install `MinGHC` and then build from the standard Windows command prompt it builds fine. But it doesn't work under the `Cygwinn` prompt (since it uses its own `sh`).

**Comment by ndmitchell** [comment] 2015-09-19 21:52
Alternatively, try `stack` - they go to more effort to set up the environment in a predictable way, making issues of what is on the PATH less problematic.

**Comment by snowleopard** [comment] 2016-01-04 13:05
I came across this issue today when installing `shake` in MSYS. I finally managed to install `old-time` with the following command:

``` sh
WHICHGHC=`which ghc` && PATH=`dirname $WHICHGHC`/../mingw/bin:$PATH && cabal install old-time
```

Maybe this will help someone.

P.S.: I stole the trick from here: http://neilmitchell.blogspot.co.uk/2010/12/installing-haskell-network-library-on.html

**Comment by hvr** [comment] 2016-01-04 13:19
Interesting... I've been using a statically set PATH including GHC's bundled `gcc` for ages on msys2... that's why I didn't notice this myself... :-/

However, that  clearly sounds like GHC's installation is to blame, resulting in an inconsistent C header environment with possibly two sets of incompatible headers, one tested at `configure`-time, and the other set actually used by GHC, and possibly a Cabal bug judging from

```
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
```

which was resolved via https://github.com/haskell/cabal/pull/2946

**Comment by ndmitchell** [comment] 2016-01-04 16:51
Removing the requirement of old-time in Shake might be feasible... I'll take a look.

**Comment by ndmitchell** [comment] 2016-01-04 18:52
@snowleopard - I can confirm old-time is only required with GHC 7.4, and only then if you are using the portable timestamp settings. Another way of saying that is that it's never actually required :). For the moment I suggest you edit out the `old-time` dependency in the `.cabal` file, and I'll mostly remove it myself shortly https://github.com/ndmitchell/shake/issues/398

**Comment by snowleopard** [comment] 2016-01-04 18:54
@ndmitchell I see, thanks!

**Comment by gbaz** [comment] 2016-06-09 19:37
Fixed with the new cabal assuming that 

```
extra-prog-path: C:\Program Files\Haskell Platform\8.0.1\msys\usr\bin
extra-lib-dirs: C:\Program Files\Haskell Platform\8.0.1\mingw\lib
extra-include-dirs: C:\Program Files\Haskell Platform\8.0.1\mingw\include
```

Or the equivalent lines for other msys/mingw locations are in your cabal config file.

**Comment by WozSoftware** [comment] 2016-09-29 09:13
just stumbled on this. gbaz is correct, the changes resolve the issue with old-time. (Win 10 64)

**Comment by gbaz** [comment] 2016-09-29 14:51
Ok, I guess we should close this issue out then.

**Closed as completed by gbaz** 2016-09-29 14:51 UTC

**Comment by melston** [comment] 2017-03-01 16:58
@gbaz , I had to add those lines to my cabal config file manually.  Thanks for that.  Is there some reason these need to be added instead of cabal finding them automatically?  I am new to cabal so I don't know how it looks for things but it seems to me that these folders are a part of the standard Haskell package so should be found without monkeying with the config file.

**Comment by gbaz** [comment] 2017-03-01 17:11
The problem is cabal is agnostic as to them, and other users may put them in different places, or have multiple msys installs, or have other versions of those binaries that don't come with msys.

I think it would be nice if cabal was better able to do autodiscovery here, or if the platform configuration process would automatically add these lines. I'm just not sure of the best way to do this in a non-fragile manner :-)

**Comment by melston** [comment] 2017-03-01 20:59
Ah, well.  I was trying to install Idris and made these changes and got a lot farther.  But then it failed at a later step.  I will have to investigate that as well.  Nothing is ever simple in this game. :)
